CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    compteType VARCHAR(50) NOT NULL,
    login VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
)

-- Table: ADMIN
CREATE TABLE ADMIN (
    ID BIGINT PRIMARY KEY,
    PRIVILEGE TEXT
)

-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    ID BIGINT PRIMARY KEY,
    LAST_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    EMAIL VARCHAR(100),
    GENDER VARCHAR(10)
)

-- Table: MERCHANT
CREATE TABLE MERCHANT (
    ID BIGINT PRIMARY KEY,
    LAST_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    EMAIL VARCHAR(100),
    LOCALISATION TEXT(250)
);




-- Table: WALLET
CREATE TABLE WALLET (
    ID BIGINT PRIMARY KEY,
    BALANCE DECIMAL(15,2)
)
